Replace `referred towards` with `referred to` throughout.
sqlalchemy/sqlalchemy pull request #10210
Opened 2023-08-08 22:32 UTC by offby1

`python3 -m tox` passes.

### Description

### Checklist

This pull request is:

- [x ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

2023-08-08 22:48 UTC, jvanasco commented
This PR addresses "referred towards", but does not address "refers towards" - which there are a few of.  Can you handle that in a second commit?

2023-08-08 22:58 UTC, offby1 commented
Oh sure, I hadn't noticed those.

On Tue, Aug 8, 2023 at 3:49 PM Jonathan Vanasco ***@***.***>
wrote:

> This PR addresses "referred towards", but does not address "refers
> towards" - which there are a few of. Can you handle that in a second commit?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sqlalchemy/sqlalchemy/pull/10210#issuecomment-1670415662>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAAYSJQFACGY4NQUEHSJALXUK66DANCNFSM6AAAAAA3JEMOPU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-09 02:32 UTC, zzzeek requested changes
if we are fixing grammar we should fix it fully, a large portion of these "refers towards" are dangling prepositions.    It's sort of why I used "towards", even though "towards" is also a preposition it felt a little less egregious.

2023-08-09 02:32 UTC, zzzeek commented on doc/build/changelog/changelog_14.rst
> +        refers to, essentially disabling the "from linting" feature, i.e. the
so.....is this a dangling preposition?   "towards" is a prep also so that would be wrong as well.  so....sentences like this would need to be fixed

2023-08-09 02:32 UTC, zzzeek commented on doc/build/changelog/changelog_14.rst
> +        caveats that the "overlaps" warning refers to, as automap is intended
dangling prep

2023-08-09 02:32 UTC, zzzeek commented on doc/build/changelog/migration_13.rst
> +kind of attribute it is referring to, e.g. scalar or collection, mapped
dp

2023-08-09 02:32 UTC, zzzeek commented on doc/build/changelog/migration_13.rst
> +mapped attribute or other descriptor or attribute that it refers to, as
dp etc...

2023-08-09 02:38 UTC, zzzeek commented
also I can't find any background on what exactly is wrong with "referred towards"

2023-08-09 02:54 UTC, offby1 commented
What's wrong with it isn't a question of "correct" or "incorrect" grammar;
it's that it was so jarring that I stopped reading, and pondered grammar,
instead of thinking about SQLAlchemy.  I've never seen that construction
before, and I'm a reasonably-literate, native English speaker.

I'm honestly not interested in carefully reading all the docs and fixing up
grammar, particularly since such fixes are likely to be contentious.  I was
hoping I could just fix the one (to me) glaring problem and move on.

On Tue, Aug 8, 2023 at 7:38 PM mike bayer ***@***.***> wrote:

> also I can't find any background on what exactly is wrong with "referred
> towards"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sqlalchemy/sqlalchemy/pull/10210#issuecomment-1670569054>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAAYSLAQSLWZUQOFVFYBULXULZ3LANCNFSM6AAAAAA3JEMOPU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-09 03:05 UTC, zzzeek commented
seeing sentences end in "referred to" is very jarring to me, even though "referred towards" is the same error, so within the realm of subjective opinion, this PR isn't improving things for me.   Using correct grammar would fix.

2023-08-09 03:07 UTC, zzzeek commented on doc/build/changelog/migration_13.rst
> +kind of attribute it is referring to, e.g. scalar or collection, mapped
e.g. 

"it became apparent early on that it also needed to make decisions about what kind of attribute to which it refers"

something like that

2023-08-09 14:52 UTC, jvanasco commented
> also I can't find any background on what exactly is wrong with "referred towards"

It's not as commonly used as "referred to".  @offby1 suggested this PR on gitter, noting "refers towards" (not "referring towards" as the first commit in this PR).  I did a quick check on the docs, and there are only 8 instances of "refers towards" in 7 files – while there are 305 instances of "refers to" in 127 files.  Standardizing those 8 into the same language as the rest made sense from a style-guide standpoint, so I suggested they submit the PR for your review.

I didn't look up "referring towards" at the time.  That is used considerably more in the docs - though it is still outnumbered by "referring to" quite a bit.

2023-08-10 20:18 UTC, jvanasco commented
> Oh sure, I hadn't noticed those.

You actually brought this up on the gitter channel citing the usage of "refers", not "referring".  There are only 8 instances of that phrase, vs 100+ of "referring".

2023-09-20 21:01 UTC, zzzeek commented
a little more chatGPTing, just to fix this up

2023-09-20 21:02 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 5d30e79c14fe78996d332fefd4bae36d76626ff4 of this pull request into gerrit so we can run tests and reviews and stuff

2023-09-20 21:02 UTC, sqla-tester commented
New Gerrit review created for change 5d30e79c14fe78996d332fefd4bae36d76626ff4: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4870

2023-09-21 13:21 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

alembic-recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4870

2023-09-21 15:12 UTC, sqla-tester commented
**Federico Caselli** (CaselIT) wrote:

looked quickly but it seems fine to me

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4870

2023-09-26 18:32 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

thanks all !

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4870

2023-09-26 18:32 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4870 has been **merged**. Congratulations! :)

2023-09-26 18:32 UTC, closed without merging