Forward `**kwargs` in `__init_subclass__` to super
sqlalchemy/sqlalchemy pull request #10733
Opened 2023-12-04 14:46 UTC by michaeloliverx

Fixes: #10732

### Description

### Checklist

This pull request is:

- [ ] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

2023-12-04 15:28 UTC, zzzeek requested changes
please add tests at https://github.com/sqlalchemy/sqlalchemy/blob/d8cab0694e6dc9f7b7fd02a4b5a8ae6bbb2e896e/test/orm/declarative/test_basic.py#L900 thanks!

2023-12-04 15:28 UTC, zzzeek commented on lib/sqlalchemy/orm/decl_api.py
> +    def __init_subclass__(cls, **kwargs: Any) -> None:
prefer **kw

2023-12-04 19:38 UTC, CaselIT commented
thanks for the update. The test could use combinations, but let's bring it in gerrit

2023-12-04 19:38 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 0a76ab159e941543ca587936928ad25beb2e3e86 of this pull request into gerrit so we can run tests and reviews and stuff

2023-12-04 19:38 UTC, sqla-tester commented
New Gerrit review created for change 0a76ab159e941543ca587936928ad25beb2e3e86: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4998

2023-12-05 21:25 UTC, sqla-tester commented
**Michael Bayer** (zzzeek) wrote:

pretty good.

to move this along, run pre-commit and also add a changelog file.  otherwise we will try to get to it...

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4998

2023-12-05 22:24 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 7fdeec1f3224f48213c9c9af5f3e7e5d0904dafa of this pull request into gerrit so we can run tests and reviews and stuff

2023-12-05 22:24 UTC, sqla-tester commented
Patchset 7fdeec1f3224f48213c9c9af5f3e7e5d0904dafa added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4998

2023-12-05 22:30 UTC, CaselIT commented
> to move this along, run pre-commit and also add a changelog file. otherwise we will try to get to it...

added to gerrit

2023-12-05 22:30 UTC, sqla-tester commented
**Federico Caselli** (CaselIT) wrote:

added changelog

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4998

2023-12-06 20:53 UTC, sqla-tester reviewed
**Michael Bayer** (zzzeek) wrote:

code review left on gerrit

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4998

* lib/sqlalchemy/dialects/mysql/base.py (line 1574): not totally sure how this got here , but if we dont fix the typo here I'll just forget about it

2023-12-06 21:05 UTC, sqla-tester reviewed
**Federico Caselli** (CaselIT) wrote:

code review left on gerrit

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4998

* lib/sqlalchemy/dialects/mysql/base.py (line 1574): Oh I think I had it locally since I fixed on 2.0 here https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5025 and I guess it got committed while pushing the changelog

2023-12-07 14:37 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4998 has been **merged**. Congratulations! :)

2023-12-07 14:37 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5009 has been **merged**. Congratulations! :)

2023-12-07 14:37 UTC, closed without merging