Use `sqlite://` over `sqlite:///:memory:`
sqlalchemy/sqlalchemy pull request #10968
Opened 2024-02-06 01:39 UTC by SamuelMarks

### Description
Your guide suggests using the empty string - https://docs.sqlalchemy.org/en/20/core/engines.html#sqlite - but that syntax is inconsistent throughout your codebase. This resolves said inconsistency.

### Checklist

This pull request is:

- [ ] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

2024-02-06 06:45 UTC, CaselIT commented
Hi,

I think it would make sense to add the memory form to the doc section you linked, so that both are listed.

The rest of the changes can be kept or not

2024-02-06 13:18 UTC, zzzeek requested changes
hi -

unfortunately I think this should be reversed, the documentation note you refer to should be amended to indicate both forms, it's entirely acceptable to use `sqlite:///:memory:` and this may be clearer as it's more explicit.

So I would revert everything here and just amend the doc section noted to indicate that both forms are acceptable.  thanks!

2024-02-06 19:50 UTC, SamuelMarks commented
Yeah I like this error message - https://github.com/sqlalchemy/sqlalchemy/blob/3a3639/lib/sqlalchemy/dialects/sqlite/pysqlite.py#L583

But consistency might be good to have regardless

2024-02-16 18:18 UTC, CaselIT commented
@SamuelMarks let us know if you don't have time to finish this

2024-03-12 22:00 UTC, closed without merging

2024-03-12 22:00 UTC, CaselIT commented
Will update that section in a separate committ