Add the write_timeout option for mysql.
sqlalchemy/sqlalchemy pull request #4385
Opened 2018-11-29 02:19 UTC by gujun4990

As MySQLdb support read_timeout and write_timeout option, and
sqlalchemy just support read_timeout option. So sqlalchemy need to add
write_timeout option.

2018-11-29 03:00 UTC, zzzeek requested changes
so there's that one line, and then there's one more thing if you can add so that it's all ready to go, add a file in the docs:    `docs/build/changelog/unreleased_12/4381.rst`   inside the file, put:

```rst
.. change::
    :tag: feature, mysql
    :tickets: 4381

    Added support for the ``write_timeout`` flag accepted by mysqlclient and pymysql to 
    be passed in the URL string.

```

that's also what we put as the second paragraph in the commit message, but I can edit that if you want.

2018-11-29 08:09 UTC, gujun4990 commented on lib/sqlalchemy/dialects/mysql/mysqldb.py
>          util.coerce_kw_type(opts, 'read_timeout', int)
OK, I will do it.

2018-11-30 05:08 UTC, zzzeek commented on lib/sqlalchemy/dialects/mysql/mysqldb.py
>          util.coerce_kw_type(opts, 'read_timeout', int)
thanks for those changes I will pull this to gerrit now, thanks!

2018-11-30 05:21 UTC, zzzeek commented
Dear contributor -

This pull request is being moved to Gerrit, at https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/988, where it may be tested and reviewed more closely.  As such, the pull request itself is being marked "closed" or "declined", however your contribution is merely being moved to our central review system. Please register at https://gerrit.sqlalchemy.org#/register/ to send and receive comments regarding this item.

2018-11-30 05:21 UTC, closed without merging