Expect ordering NULLs to work on sqlite >= 3.30.
sqlalchemy/sqlalchemy pull request #4921
Opened 2019-10-17 16:31 UTC by nphilipp

Signed-off-by: Nils Philippsen <nils@tiptoe.de>

This fixes one test I mentioned in issue #4920.

### Description

SQlite 3.30 introduced support for ordering NULLs. The current tests didn't reflect that, this PR fixes it.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

2019-10-18 02:29 UTC, zzzeek requested changes
can you add "sqlite" also to the list of skips under `@nested_aggregates` ? that way we can fix both issues at once.

2019-11-02 21:36 UTC, zzzeek commented
wow lost track of this

2019-11-02 21:36 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work to try to get revision e18534a9045786efdaf4963515222838c62e0300 of this pull request into gerrit so we can run tests and reviews and stuff

2019-11-02 21:36 UTC, sqla-tester commented
New Gerrit review created for change e18534a9045786efdaf4963515222838c62e0300: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1557

2019-11-04 18:23 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

2019-11-04 18:23 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/1557 has been **merged**. Congratulations! :)

2019-11-04 18:24 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

2019-11-04 18:24 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/1558 has been **merged**. Congratulations! :)

2019-11-04 18:24 UTC, closed without merging