Add public accessor to for `is_single_entity` to Query class
sqlalchemy/sqlalchemy pull request #4935
Opened 2019-10-22 17:18 UTC by pfhayes

### Description
This is useful when writing middleware between your application
and sqlalchemy, to inspect what type of results we will be seeing.

As an example,

```
    def issue_query_and_wrap_results(query, Wrapper):
      results = query.all()
      for result in results:
        if q.is_single_entity:
          return Wrapper(result)
        else:
          return tuple(Wrapper(r) for r in result)
```
    
Without this accessor, you need to inspect the return results or private members of the
query and try to guess the intent

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

Fixes: #4934

2019-10-23 17:45 UTC, zzzeek requested changes
small changes.  if you'd like me to take over, just say the word.

2019-10-23 17:45 UTC, zzzeek commented on lib/sqlalchemy/orm/query.py
> +        result list, and False if this query returns a tuple of entities for each result.
I think this is going to fail pep8 because we use 79 character lines

2019-10-23 17:45 UTC, zzzeek commented on lib/sqlalchemy/orm/query.py
> +        """
can you add:

```
    .. versionadded:: 1.3.11

    .. seealso::

        :meth:`.Query.only_return_tuples`

```
also add to "def only_return_tuples":

```
    .. seealso::
        :attr:`.Query.is_single_entity`
```

2019-10-23 17:45 UTC, zzzeek commented on lib/sqlalchemy/orm/query.py
> +        """Returns True if this query returns a single entity for each instance in its
add a single summary line at the top:

```
"indicate if this :class:`.Query` returns tuples or single entities"
```
then a newline, then the paragraph you have here.

2019-10-23 17:45 UTC, zzzeek commented on test/orm/test_query.py
> +        assert query.is_single_entity is True
can you use is_true(query.is_single_entity) for these

from sqlalchemy.testing import is_true

2019-10-23 17:45 UTC, zzzeek commented on test/orm/test_query.py
> +        assert query.is_single_entity is False
from sqlalchemy.testing import is_false

2019-10-23 17:45 UTC, zzzeek commented on test/orm/test_query.py
> +        assert query.is_single_entity is False
ditto

2019-10-23 22:39 UTC, pfhayes commented
@zzzeek thanks for your feedback! addressedd

2019-10-24 14:11 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work to try to get revision 98f72b40a896761a65b048cc3722ff2dac4cf2b1 of this pull request into gerrit so we can run tests and reviews and stuff

2019-10-24 14:11 UTC, sqla-tester commented
New Gerrit review created for change 98f72b40a896761a65b048cc3722ff2dac4cf2b1: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1542

2019-10-24 14:11 UTC, zzzeek commented
very nice

2019-10-25 04:35 UTC, pfhayes commented
great! I'm not familiar with gerritt, anything else needed from me here?

2019-10-25 13:21 UTC, zzzeek commented
> great! I'm not familiar with gerritt, anything else needed from me here?

nope, I'll finish it up but I have a lot of emails / issues that are working through pls be patient

2019-10-25 15:47 UTC, pfhayes commented
Thanks! No rush on my end. I appreciate your help!

On Fri, Oct 25 2019 at 6:21 AM, < notifications@github.com > wrote:

> 
> 
>> 
>> 
>> great! I'm not familiar with gerritt, anything else needed from me here?
>> 
>> 
> 
> 
> 
> nope, I'll finish it up but I have a lot of emails / issues that are
> working through pls be patient
> 
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub (
> https://github.com/sqlalchemy/sqlalchemy/pull/4935?email_source=notifications&email_token=AADCNHGMFVKTPZZKFZU7UKLQQLXFHA5CNFSM4JDSZ74KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECIKRFY#issuecomment-546351255
> ) , or unsubscribe (
> https://github.com/notifications/unsubscribe-auth/AADCNHFSBEB5ALUEBTUKHNTQQLXFHANCNFSM4JDSZ74A
> ).
> 
> 
>

2019-10-28 12:46 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

2019-10-28 12:46 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/1542 has been **merged**. Congratulations! :)

2019-10-28 12:46 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

2019-10-28 12:46 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/1549 has been **merged**. Congratulations! :)

2019-10-28 12:46 UTC, closed without merging