Improve regex parsing of CHECK constraints.
sqlalchemy/sqlalchemy pull request #5044
Opened 2019-12-18 14:51 UTC by gordthompson

Fixes: #5039

### Description
Avoid parse warnings for PostgreSQL CHECK constraints that are a simple function call.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

2019-12-18 15:58 UTC, zzzeek requested changes
looks good, lets use fixtures for the test case.  thanks!

2019-12-18 15:58 UTC, zzzeek commented on test/dialect/postgresql/test_reflection.py
>      def test_reflect_check_constraint(self):
add the @testing.provide_metadata decorator

2019-12-18 15:58 UTC, zzzeek commented on test/dialect/postgresql/test_reflection.py
> +        sql = text("""\
create this object as a DDL() object instead of text()

2019-12-18 15:58 UTC, zzzeek commented on test/dialect/postgresql/test_reflection.py
> +        testing.db.execute(sql)
associate the DDL object with the metadata that the decorator gives us:

```
event.listen(
    self.metadata,
    "before_create",
    DDL("CREATE OR REPLACE FUNCTION ...")
)
```

at the same time, associate the "drop" DDL also:

`event.listen(self.metadata, "after_drop", DDL("DROP FUNCTION is_positive"))`

2019-12-18 15:58 UTC, zzzeek commented on test/dialect/postgresql/test_reflection.py
> +            sql = text("DROP FUNCTION IF EXISTS is_positive")
the DROP FUNCTION is now handled by our "after_drop" listener above

2019-12-18 15:58 UTC, zzzeek commented on test/dialect/postgresql/test_reflection.py
> +            sql = text("DROP TABLE IF EXISTS pgsql_cc")
dropping of the table is performed by the `@testing.provide_metadata` decorator

2019-12-18 15:58 UTC, zzzeek commented on test/dialect/postgresql/test_reflection.py
> +        except:
don't need the except/raise as the `@testing.provide_metadata` fixture will handle the drops

2019-12-18 15:58 UTC, zzzeek commented on test/dialect/postgresql/test_reflection.py
> +            reflected = Table("pgsql_cc", MetaData(testing.db),
the newer syntax here is:

    reflected = Table("pgsql_cc", MetaData(), autoload_with=testing.db)

2019-12-18 23:26 UTC, gordthompson commented
The beginning of the test now looks like this:

```python
    @testing.provide_metadata
    def test_reflect_check_constraint(self):
        meta = self.metadata

        udf_create = """\
            CREATE OR REPLACE FUNCTION is_positive(
                x integer DEFAULT '-1'::integer)
                RETURNS boolean
                LANGUAGE 'plpgsql'
                COST 100
                VOLATILE 
            AS $BODY$BEGIN
                RETURN x > 0;
            END;$BODY$;
        """
        sa.event.listen(meta, "before_create",
                        sa.DDL(udf_create))
        sa.event.listen(meta, "after_drop",
                        sa.DDL("DROP FUNCTION is_positive"))

        cc_table = Table(
            "pgsql_cc",
            meta,
            Column("a", Integer()),
            CheckConstraint("a > 1 AND a < 5", name="cc1"),
            CheckConstraint("a = 1 OR (a > 2 AND a < 5)", name="cc2"),
            CheckConstraint("is_positive(a)", name="cc3"),
        )

        cc_table.create()
```

Unfortunately, the CREATE FUNCTION is not getting sent (at all; see attached log), so the CREATE TABLE fails. However, the DROP FUNCTION *is* getting sent, so that fails, too.

[postgresql.log](https://github.com/sqlalchemy/sqlalchemy/files/3980947/postgresql.log)

2019-12-19 01:32 UTC, zzzeek commented
yes call metadata.create_all() instead of table.create()

2019-12-19 11:51 UTC, gordthompson commented
Yup, that did the trick. Thanks.

2019-12-19 13:49 UTC, zzzeek commented
are you interested in writing changelog files ?

2019-12-19 15:01 UTC, gordthompson commented
> are you interested in writing changelog files ?

Sure, I could give it a bash. Just create a 5039.rst file? Right now it looks like they all live in the unreleased_14 folder.

2019-12-19 15:04 UTC, zzzeek commented
OK so, this is a bug that we are targeting at 1.3.x, so it goes into unreleased_13.     but yes thanks!

2019-12-19 16:08 UTC, zzzeek commented on doc/build/changelog/unreleased_13/5039.rst
> +    reflected CHECK constraint that was a boolean-valued *function*
I would remove the asterisks because they create awkward italics.

2019-12-19 17:20 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work to try to get revision b6903c656422abf658c4cc88b8cd03291d3a50f8 of this pull request into gerrit so we can run tests and reviews and stuff

2019-12-19 17:20 UTC, sqla-tester commented
New Gerrit review created for change b6903c656422abf658c4cc88b8cd03291d3a50f8: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1623

2019-12-19 18:28 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

so on older Posgresql 9.6, we're getting this error:

psycopg2.errors.SyntaxError: syntax error at end of input
LINE 1: DROP FUNCTION is_positive

does CREATE FUNCTION  / DROP FUNCTION not exist on PG 9?  we can add an exclusion rule to the test if this is the case.

2019-12-19 19:01 UTC, gordthompson commented
Ah, it appears that `DROP FUNCTION` without the argument type(s) is only supported in 10+.

```sql
DROP FUNCTION is_positive(integer)
```

works in 12.1 and it should work in 9.6 as well.

2020-01-03 19:27 UTC, sqla-tester commented
**Gord Thompson** (gordthompson) wrote:

The pep8/1843 failure "F841 local variable 'cc_table' is assigned to but never used" looks like a new rule. (I have already found the one bloody space that triggered the "trailing whitespace" failure, which also appears to be a new rule.) The sqlalchemy_gerrit/3577 failure looks like a transient.

2020-01-03 21:28 UTC, zzzeek commented
> **Gord Thompson** (gordthompson) wrote:
> 
> The pep8/1843 failure "F841 local variable 'cc_table' is assigned to but never used" looks like a new rule. (I have already found the one bloody space that triggered the "trailing whitespace" failure, which also appears to be a new rule.) The sqlalchemy_gerrit/3577 failure looks like a transient.

F841 has been in for awhile.  I'm working on F821 in https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1649/ but F841 was in since 190e0139e834e4271268652e058c

2020-01-04 00:37 UTC, gordthompson commented
Yup, you're right. We had to change `cc_table.create()` to `metadata.create_all()` and that got rid of the usage. Anyway, we're passing now.

2020-01-18 15:42 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

2020-01-18 15:42 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/1623 has been **merged**. Congratulations! :)

2020-01-18 15:43 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

2020-01-18 15:43 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/1672 has been **merged**. Congratulations! :)

2020-01-18 15:43 UTC, closed without merging