added docstring about expire_on_commit for #5243
sqlalchemy/sqlalchemy pull request #5328
Opened 2020-05-14 20:03 UTC by jvanasco

### Description
docstring

### Checklist
This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed

Instead of clarifying section 2 (as suggested in #5243), I added a new paragraph as this is related to both section 1 & 2.

I tried to keep this as generic as possible.

I can't get docs to build right, so I do have a concern about this link:

   :paramref:`_sa.orm.session.Session.expire_on_commit`

I think that is the correct formatting, but wanted to call attention to it.

2020-05-16 20:56 UTC, zzzeek commented
@jvanasco  do you have an interest in creating reviews right in gerrit?  otherwise I could give you access to add sqla_tester to these.... (they still go through pep8 check in CI)

2020-05-16 20:56 UTC, zzzeek commented
well not for .rsts...OK

2020-05-16 20:58 UTC, zzzeek commented on doc/build/errors.rst
> +Please note: the default setting of :paramref:`_sa.orm.session.Session.expire_on_commit`
might as well use

   .. note::

2020-05-16 21:02 UTC, zzzeek requested changes

2020-05-16 21:02 UTC, zzzeek commented on doc/build/errors.rst
> +query the database to refresh the instance and attributes.
```

See the section :ref:`session_committing` for further background on this.

```

2020-05-16 21:02 UTC, zzzeek commented on doc/build/errors.rst
> +query the database to refresh the instance and attributes.
also in "seealso" below:

```
    :ref:`session_committing` - background on session commit
    :ref:`session_expire` - background on attrifbute expiry
```

2020-05-17 01:20 UTC, jvanasco commented
Yes I can do either to make things easier for all

> On May 16, 2020, at 4:56 PM, mike bayer <notifications@github.com> wrote:
> 
> ﻿
> @jvanasco do you have an interest in creating reviews right in gerrit? otherwise I could give you access to add sqla_tester to these.... (they still go through pep8 check in CI)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-05-19 17:32 UTC, decaz commented on doc/build/errors.rst
> +    :ref:`session_expire` - background on attrifbute expiry
attr**ib**ute

2020-05-19 18:38 UTC, jvanasco commented on doc/build/errors.rst
> +    :ref:`session_expire` - background on attrifbute expiry
ha! thanks.

2020-09-04 23:48 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **jvanasco** to try to get revision e760ed4ef1749aadfb8d63d776c764d98b93b1e5 of this pull request into gerrit so we can run tests and reviews and stuff

2020-09-04 23:48 UTC, sqla-tester commented
New Gerrit review created for change e760ed4ef1749aadfb8d63d776c764d98b93b1e5: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2211

2020-09-24 19:57 UTC, sqla-tester commented
**Jonathan Vanasco** (jvanasco) wrote:

Workflow+1

I found this in Gerrit while cleaning up Github. Sorry for sitting on it.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2211

2020-10-26 14:54 UTC, sqla-tester reviewed
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

(1 comment)

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2211

* doc/build/errors.rst (line 856): this is top-level information for this use case and "expire" is the default, so I will change this to be a non-note paragraph.

2020-10-26 14:54 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

Verified+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2211

2020-10-26 14:54 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2211 has been **merged**. Congratulations! :)

2020-10-26 14:55 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

Verified+1 Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2328

2020-10-26 14:55 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2328 has been **merged**. Congratulations! :)

2020-10-26 14:55 UTC, closed without merging