Support legacy select(<iterable>) in addition to select(<list>) in v1.4
sqlalchemy/sqlalchemy pull request #5936
Opened 2021-02-12 23:04 UTC by olirice

### Description
In v1.3 `sqlalchemy.select` supports an arbitrary iterable as the first argument. In v1.4 there was a minor regression that limits the first argument to a `list`. This change re-allows an iterable first argument

Resolves #5935

### Checklist
This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

2021-02-12 23:49 UTC, zzzeek commented on lib/sqlalchemy/sql/selectable.py
> +        if (args and hasattr(args[0], '__iter__')) or kw:
unfortunately strings have an ` __iter__` method also, so this interferes with an error condition we have for the newer style:

```
>>> from sqlalchemy import select
>>> select("foo")
Traceback (most recent call last):
...
sqlalchemy.exc.ArgumentError: Textual column expression 'f' should be explicitly declared with text('f'), or use column('f') for more specificity

```

one way to sneak around this, which we would need to really accept "iterable", is to check for a string-based method also:

    if hasattr(x, "__iter__") and not hasattr(x, "strip")

we have some other code that uses that one specifically.

2021-02-12 23:49 UTC, zzzeek commented on test/sql/test_deprecations.py
>      def test_select_kw_argument(self):
I'd want to test your ".c" case explicitly here as well.

2021-02-12 23:50 UTC, zzzeek requested changes
two changes suggested...

2021-02-12 23:50 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision de85ad51009101b8b946d34265bd21842e127dbb of this pull request into gerrit so we can run tests and reviews and stuff

2021-02-12 23:50 UTC, sqla-tester commented
New Gerrit review created for change de85ad51009101b8b946d34265bd21842e127dbb: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2584

2021-02-13 00:17 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 633ff12af04f9e0d22c6a56b972ad8c2b91d08f3 of this pull request into gerrit so we can run tests and reviews and stuff

2021-02-13 00:17 UTC, sqla-tester commented
Patchset 633ff12af04f9e0d22c6a56b972ad8c2b91d08f3 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2584

2021-02-13 00:24 UTC, olirice commented
This change impacting more of the test suite than I expected

Closing until I can work through those test failures

Sorry for the noise, I'll re-open when its ready for review

2021-02-13 02:46 UTC, zzzeek commented
I think just doing "isinstance(list, ColumnCollectionThing)" is likely what it should be for now, the compatiblity check at that spot is kind of intense

2021-02-13 19:06 UTC, olirice commented
sounds good, thanks for the help

updated

2021-02-13 19:21 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **gordthompson** to try to get revision 575ab3e7df30fc8da03752d102c8eeb6cb3a3e3d of this pull request into gerrit so we can run tests and reviews and stuff

2021-02-13 19:21 UTC, sqla-tester commented
Patchset 575ab3e7df30fc8da03752d102c8eeb6cb3a3e3d added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2584

2021-02-14 14:44 UTC, sqla-tester commented
**Gord Thompson** (gordthompson) wrote:

I assume this needs a changelog entry.Otherwise, lgtm.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2584

2021-02-14 19:24 UTC, gordthompson commented
Changelog file added to Gerrit.

https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2584

2021-02-15 19:07 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

recheck

that had to be a false positive...

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2584

2021-02-15 19:33 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2584 has been **merged**. Congratulations! :)

2021-02-15 19:33 UTC, closed without merging