fix(mypy): Placeholder vars should have fullname set
sqlalchemy/sqlalchemy pull request #7348
Opened 2021-11-19 20:53 UTC by jaens

Otherwise the dmypy daemon will crash on an incremental re-run.

### Description

Fixes #7347 (see that for more details).

Made against the 1.4 branch since this is what I reproduced it on, but it also works and should be cherry-pickable on main.

2022-01-05 14:17 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 79eefa3417e09a8f9defaeafdb9f76d323385238 of this pull request into gerrit so we can run tests and reviews and stuff

2022-01-05 14:17 UTC, sqla-tester commented
New Gerrit review created for change 79eefa3417e09a8f9defaeafdb9f76d323385238: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3482

2022-01-05 14:19 UTC, sqla-tester reviewed
**mike bayer** (zzzeek) wrote:

needs:

1. doc/build/changelog/unreleased_14/7347.rst file 

2. needs to be against main, with cherry-pick back to 1.4 we can do that here separately

3. clean up commit message

thanks!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3482

* /COMMIT_MSG (line 13): format this as:

Fixes: #7347


no extra characters
* /COMMIT_MSG (line 15): needs to be against main first, with cherry pick back to 1.4
* /COMMIT_MSG (line 21): remove this from commit message

2022-01-07 22:19 UTC, zzzeek requested changes
hey there -

I wanted this to be against main branch, we can backport more easily than forwards-port (at least I can with my local setup), also someone needs to add a changelog file doc/build/changelog/unreleased_14/7347.rst  and also we need to remove the extra formatting / images etc. from the changelog message.

2022-01-09 21:03 UTC, CaselIT commented
I'll add the changelog and change target branch in the week

2022-01-15 09:46 UTC, sqla-tester commented
**Federico Caselli** (CaselIT) wrote:

Added main patch and changelog

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3482

2022-01-15 14:08 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3526 has been **merged**. Congratulations! :)

2022-01-15 14:09 UTC, closed without merging

2022-01-15 14:09 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3482 has been **merged**. Congratulations! :)