Adding typing to Postgres dialect file.
sqlalchemy/sqlalchemy pull request #9594
Opened 2023-04-04 02:04 UTC by Gamrix

Adding typing information for various parameters for Postgres types (in accordance to the docs).

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

2023-04-04 07:02 UTC, CaselIT requested changes
Thanks for the effort, a few pointers

2023-04-04 07:02 UTC, CaselIT commented on lib/sqlalchemy/dialects/postgresql/types.py
> +    def __init__(self, timezone=False, precision: Optional[int] = None):
Timezone should also be typed

2023-04-04 07:02 UTC, CaselIT commented on lib/sqlalchemy/dialects/postgresql/types.py
>  # mypy: ignore-errors
This should be removed once the types are added

2023-04-11 20:08 UTC, CaselIT commented
Thanks, let's see what the pipeline says

2023-04-12 06:34 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision c7e39a219108f9e81ad22c008a664b62f09f9d5f of this pull request into gerrit so we can run tests and reviews and stuff

2023-04-12 06:35 UTC, sqla-tester commented
New Gerrit review created for change c7e39a219108f9e81ad22c008a664b62f09f9d5f: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4563

2023-04-25 16:44 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4563 has been **merged**. Congratulations! :)

2023-04-25 16:44 UTC, closed without merging