comment fix: QueuePool is now default for SQLite
sqlalchemy/sqlalchemy pull request #9734
Opened 2023-05-03 00:22 UTC by shrichards

### Description
I removed a portion of the `QueuePool` class comment which indicated that `QueuePool` is not the default pool used by the SQLite dialect.

As of SqlAlchemy 2.0, `QueuePool` is the default for SQLite (https://github.com/sqlalchemy/sqlalchemy/commit/22ed657827b487df9012def07271aed01bd4ae12)

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

2023-05-03 11:45 UTC, CaselIT commented
Hi, thanks for the fix.

Not sure if it makes sense to mention that sqlite memory still don't use it. @zzzeek

2023-05-08 20:40 UTC, zzzeek commented
OK this is two separate PRs from different people both getting at the sqlite thing, e.g. #9747 and #9734 right?

2023-05-08 20:42 UTC, zzzeek requested changes

2023-05-08 20:42 UTC, zzzeek commented on lib/sqlalchemy/pool/impl.py
> -    all :class:`_engine.Engine` objects, unless the SQLite dialect is in use.
OK like I said at #9747, this should say, "unless the SQLite dialect is in use with a "memory" database"

2023-05-08 22:36 UTC, CaselIT commented
> OK this is two separate PRs from different people both getting at the sqlite thing, e.g. #9747 and #9734 right?

yep

2023-05-26 19:28 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision f956a5ee0451f8580dbe4e9b28985e7456c6c8a1 of this pull request into gerrit so we can run tests and reviews and stuff

2023-05-26 19:28 UTC, sqla-tester commented
New Gerrit review created for change f956a5ee0451f8580dbe4e9b28985e7456c6c8a1: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4634

2023-05-26 22:40 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4634 has been **merged**. Congratulations! :)

2023-05-26 22:40 UTC, closed without merging